### ISSUE TITLE
Relevant provisioning metrics should be collected

### ISSUE THREAD

**Issue by Disper** [kyma-project/infrastructure-manager#192] opened 2024-04-25 10:00 UTC
**Reason**
Correctly collected metrics are required to ensure that KIM is working as expected on all landscapes.

**Acceptance Criteria**
- [ ] Ask SRE about preferred metrics
- [ ] Consider what's already gathered in KEB and what additionally would be useful in KIM
- [ ] Plutono metrics configuration should be persisted and their should be available on DEV/STAGE landscapes 

Metrics ideas:
- Collect provisioning statuses (how many clusters are successfully provisioned/failed provisionings/in progress)

**Attachments**
- [Related improvements issue in kubeconfig metrics](https://github.com/kyma-project/infrastructure-manager/issues/180)
- [prometheus best practices](https://prometheus.io/docs/practices/naming/)

**Comment by tobiscr** [comment] 2024-06-26 10:43
Duplicate of #113

**Closed by tobiscr** 2024-06-26 10:43 UTC
