### ISSUE TITLE
Add validation for `Runtime` CRs created via KEB and that are available as samples 

### ISSUE THREAD

**Issue by Disper** [kyma-project/infrastructure-manager#244] opened 2024-05-31 08:13 UTC
**Why**
Runtime CRs has to have a valid values, otherwise invalid clusters might be created.

**Should cover scenarios**
- [ ] Provisioning
- [ ] Upgrade

**What has to be validated**
- [ ] ensure that required values are non-empty (verify whole CRD, each field)

**Note**
Idea to start by adding that as a part of the state machine, then validation webhook could be considered.

**Comment by tobiscr** [comment] 2024-12-05 09:13
Duplicate of #229

**Comment by tobiscr** [comment] 2024-12-05 09:14
closing as duplicate - we will continue in #229

**Closed by tobiscr** 2024-12-05 09:14 UTC
