### ISSUE TITLE
Provisioner should persist shoots under a feature flag and not manage runtimes

### ISSUE THREAD

**Issue by Disper** [kyma-project/infrastructure-manager#264] opened 2024-06-14 07:59 UTC
To consider - could be either done under feature flags 
Then consider creating a follow-up for label based approach

**Comment by Disper** [comment] 2024-06-24 11:27
part of the implementation #3433 
(still missing is flag is not managing)

To consider - could be either done under the labels or feature flags

**Comment by tobiscr** [comment] 2024-07-25 08:41
Duplicate of #250

**Closed by tobiscr** 2024-07-25 08:41 UTC
