### ISSUE TITLE
Migrate from GardenerCluster CR to KIM

### ISSUE THREAD

**Issue by Disper** [kyma-project/infrastructure-manager#251] opened 2024-06-03 11:23 UTC
**Description**
- KEB should no longer create `Gardener Cluster`CRs
- KIM should create those CR
- (optional) Either now, or in a separate ticket change the name to a more meaningful name like `Kubeconfig`

**Reasons**
- KEB should no longer create `Gardener Cluster` CRs
- `Gardener Cluster` CR name is confusing in the current architecture as it is only responsible for managing kubeconfig secrets

**Attachments**
See https://github.com/kyma-project/infrastructure-manager/issues/187 for ideas

**Comment by tobiscr** [comment] 2024-07-25 08:43
Duplicate of #282

**Closed by tobiscr** 2024-07-25 08:43 UTC
Labels: kind/feature, area/control-plane
