### ISSUE TITLE
KIM should validate relevant parts of the shoot spec when `Runtime` CR is updated

### ISSUE THREAD

**Issue by Disper** [kyma-project/infrastructure-manager#208] opened 2024-05-10 06:52 UTC
**Description**
Some fields in Shoot-Spec could be updated independent to the `RuntimeCR` (e.g. update of Kubernetes images etc.).

We have to agree and implement a strategy how we deal with such cases, also considering if a change to an immutable field (of Shoot-Spec) would be required.

AC:

- [x] **Validation**. Agree on a strategy how we deal with changes applied on the Shoot-Spec (e.g. Deny modifications to particular fields in Shoot-Spec CR if some values were modified by Gardener, Sync back Shoot-Spec changes to Runtime CR etc. etc.) (e.g. using webhook)
    - [ ] Verify the available approaches with it's Pros / Cons and prepare a recommendation for the strategy
    - [x] Share and agree the strategy within the team
    - [x] Should not allow improper modification

**Comment by Disper** [comment] 2024-06-13 07:42
Connected to #198

**Comment by Disper** [comment] 2024-06-20 09:33
Extracted parts of it to a separate issue https://github.com/kyma-project/infrastructure-manager/issues/270

**Comment by tobiscr** [comment] 2024-07-22 11:24
Duplicate of https://github.com/kyma-project/infrastructure-manager/issues/232

**Closed** 2024-07-22 11:24 UTC
